### ISSUE TITLE
"pixelate" shader has multiple distortions with force integer scaling

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#309]
I reported this on Discord, but I found some new things, and I though an issue might help consolidate it.

Here's a region from the Shrek 2 (GBA) title screen comparing SkyEmu at `2x` size (left) to NanoBoyAdvance at `1x` size (right):

![Shrek 2 title screen, highlighting a horsey](https://github.com/skylersaleh/SkyEmu/assets/30182911/6c7e0742-faf4-46e9-a0b1-93bebd006712)

I also realized `1x` size also has issues, so I made a comparison for it as well.

![Shrek_2_SkyEmu_pixelate_1x](https://github.com/skylersaleh/SkyEmu/assets/30182911/0f823f67-2955-4b08-b7dc-13829baad63d)

(For the second one, I checked at `2x` as well, and it's a shader issue with `1x`, not an emulation issue: [same screen at 2x](https://github.com/skylersaleh/SkyEmu/assets/30182911/604ae3e2-b03d-43df-b540-971366c9cce5)).

### Platform

- Windows 11 using SkyEmu dev build 752d340

**Comment by skylersaleh** [comment]
Could you see if you can reproduce this using the web build? 

I want to make sure it isn't a DX vs OGL vs. Metal sampling convention issue.

**Comment by skylersaleh** [comment]
I tweaked the shaders a bit and was able to make the quality a lot better on my machine with some changes I just pushed to dev. Can you try the latest dev build [here](https://github.com/skylersaleh/SkyEmu/pull/143) and see if it also fixes things on your side? 

<img width="613" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/035e4be4-6113-4d4f-bbba-c0738f7ab501">

**Comment by RetroEdit** [comment]
In aeada92, the newest version, I tested scale factors `1x` through `6x`. A scale factor of `5x` still had some horizontal distortions in the text at the top and in the bottom-right.

![SkyEmu_pixelate_5x](https://github.com/skylersaleh/SkyEmu/assets/30182911/1a0e8ac7-380d-478e-83fb-4a4ad4757d3e)

I also tested on the web version, but it only happened on Windows. So this might be a separate DirectX issue.

**Comment by skylersaleh** [comment]
This is sort of a shot in the dark, but it might help. 

https://github.com/skylersaleh/SkyEmu/commit/104c287b30c1f0ddc36d1970def9c82ca402b91b

**Comment by RetroEdit** [comment]
Nope, this doesn't seem to fix it. I'm happy using other scale factors, though, so it is somewhat low priority, but I do think it's probably desirable to fix long-term.

**Comment by skylersaleh** [comment]
I suspect this change may fix this on your machine. 

https://github.com/skylersaleh/SkyEmu/commit/f55903a8bccc3627d87a633ea36a0f4e09b19603

Can you give the latest dev a try (in about 15 mins after it is done building)?

**Comment by RetroEdit** [comment]
Looks good to me.
