### ISSUE TITLE
Action replay codes not able to be typed in

### ISSUE THREAD

**Issue by ambudoodles** [skylersaleh/SkyEmu#496]
![Image](https://github.com/user-attachments/assets/c66e6c18-941a-457c-9480-78ebbd8a7ded)

![Image](https://github.com/user-attachments/assets/bfd61236-f2b6-4c60-aa3b-9367bad31e16)
![Image](https://github.com/user-attachments/assets/c9f04712-2eae-4e2c-a0c4-3b758f7c6ce8)
![Image](https://github.com/user-attachments/assets/ff6b2380-5dd4-4427-a740-4b7f08a1375b)
![Image](https://github.com/user-attachments/assets/958db4c7-6e5c-4f82-a9d1-1177fd72c471)

**Comment by OFFTKP** [comment]
Reproduced on Android browsers (Chrome, Brave), but not on iOS browsers

Related bug: https://github.com/ocornut/imgui/issues/5133

**Comment by OFFTKP** [comment]
It seems that backspace works (ie. on Untitled Code box), this suggests that keys go through but not characters

**Comment by skylersaleh** [comment]
We had a similar issue on the Android native build where some of the soft keyboards were sending characters instead of keys. Unfortunately there, it was impossible to fix nicely as some soft keyboards sent both characters and keys, which made it not possible to type if we counted characters and keys. 

The way we fixed it there was that we created a native android text field that was invisible that overlaid the UI and had a system that converted messages into that into something that imgui could understand. https://github.com/skylersaleh/SkyEmu/blob/999aa3433ff0f8c4e7bc086157ba4016900699e6/tools/android_project/app/src/main/java/com/sky/SkyEmu/EnhancedNativeActivity.java#L117

**Comment by GalaxyM105** [comment]
> We had a similar issue on the Android native build where some of the soft keyboards were sending characters instead of keys. Unfortunately there, it was impossible to fix nicely as some soft keyboards sent both characters and keys, which made it not possible to type if we counted characters and keys. 
> 
> The way we fixed it there was that we created a native android text field that was invisible that overlaid the UI and had a system that converted messages into that into something that imgui could understand. https://github.com/skylersaleh/SkyEmu/blob/999aa3433ff0f8c4e7bc086157ba4016900699e6/tools/android_project/app/src/main/java/com/sky/SkyEmu/EnhancedNativeActivity.java#L117

I tested the Android native Dev build and it's still not letting me backspace in Action Replay. Has the fix that you mentioned not been applied to the Dev release yet?
